version: 0.2
phases:
  build:
    commands:
      - pip install -r requirements.txt
      - npm install -g aws-cdk
      - python -m pip install aws_cdk.aws_apigateway
      - cdk deploy
artifacts:
  files:
    - '**/*'
